
development:
  adapter: postgresql
  encoding: unicode
  database: {{db_name}}_development
  pool: 5
  username: {{db_username}}
  password: {{db_password}}

test:
  adapter: postgresql
  encoding: unicode
  database: {{db_name}}_test
  pool: 5
  username: {{db_username}}
  password: {{db_password}}

production:
  adapter: postgresql
  encoding: unicode
  database: {{db_name}}_development
  pool: 5
  username: {{db_username}}
  password: {{db_password}}
